export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const INITIALIZE_LOADER = "INITIALIZE_LOADER";
export const RESET_LOADING = "RESET_LOADING";
export const INITIALIZE_FORM = "INITIALIZE_FORM";
export const FORM_SUCCESS = "FORM_SUCCESS";
export const FORM_SUBMITTING = "FORM_SUBMITTING";
export const RESET_FORM_SUBMITTING = "RESET_FORM_SUBMITTING";

export const FETCH_BLOG_LIST = "FETCH_BLOG_LIST";
export const SET_BLOG_LIST = "SET_BLOG_LIST";
export const FETCH_BLOG_ERROR = "FETCH_BLOG_ERROR";
export const SET_BLOG_DETAIL = "SET_BLOG_DETAIL";
export const RESET_BLOG_DETAIL = "RESET_BLOG_DETAIL";
export const FETCH_PORTFOLIO_LIST = "FETCH_PORTFOLIO_LIST";
export const SET_PORTFOLIO_LIST = "SET_PORTFOLIO_LIST";
export const FETCH_PORTFOLIO_ERROR = "FETCH_PORTFOLIO_ERROR";
export const SET_PORTFOLIO_DETAIL = "SET_PORTFOLIO_DETAIL";
export const RESET_PORTFOLIO_DETAIL = "RESET_PORTFOLIO_DETAIL";
export const FETCH_PARTNERSHIP_ERROR = "FETCH_PARTNERSHIP_ERROR";
export const FETCH_PARTNERSHIP_LIST = "FETCH_PARTNERSHIP_LIST";
export const SET_PARTNERSHIP_LIST = "SET_PARTNERSHIP_LIST";

export const FETCH_EVENT_LIST = "FETCH_EVENT_LIST";
export const SET_EVENT_LIST = "SET_EVENT_LIST";
export const FETCH_EVENT_ERROR = "FETCH_EVENT_ERROR";
export const SET_EVENT_DETAIL = "SET_EVENT_DETAIL";
export const RESET_EVENT_DETAIL = "RESET_EVENT_DETAIL";

export const FETCH_HOME_LIST = "FETCH_HOME_LIST";
export const SET_HOME_LIST = "SET_HOME_LIST";
export const FETCH_HOME_ERROR = "FETCH_HOME_ERROR";
